### ISSUE TITLE
Support for Union class. 

### ISSUE THREAD

**Issue by arogozhnikov** [LukasMasuch/streamlit-pydantic#10]
Cool project @LukasMasuch, thank you!

**Feature description:**

I'm missing support for Unions. Ver simple example can be:

```
class PostalAddress(BaseClass):
    street: str
    city: str
    house: int
    
class EmailAddress(BaseClass):
    email: str
    send_news: bool
    
class ContactMethod(BaseClass):
    contact: Union[PostalAddress, EmailAddress]
    ... other fields
    
    
# rendring form for ClassMethod

```

So far I'm doing it with radio button, depending on its output the right option is rendered. 

I'm not sure if there is more elegant solution, but let me know if you have ideas so I could help with implementing

**Comment by LukasMasuch** [comment]
Hey @arogozhnikov,

Thanks for the suggestion. I have just implemented an initial support for union by using a selectbox (this will be rolled out with the next version):

![image](https://user-images.githubusercontent.com/2852129/139959370-23a492ad-888b-45ac-9da6-1965878634c6.png)

However, this currently has some downsides: 
- Does not work within a form (only works with `pydantic_input`), since a form cannot have interactive elements.
- Only supports object references as union types (no lists, or basic types).

Would this help with your usecase?
