### ISSUE TITLE
Handle Collection Type fields

### ISSUE THREAD

**Issue by papalotis** [LukasMasuch/streamlit-pydantic#9]
**Feature description:**
Correctly handle fields such as `List[str]`

Curently when a field is of a collection type such as `dict, list, Mapping, Sequence` etc. the behaviour is broken.
For the model 
```python
class ExampleModel(BaseModel):
        text: str
        many_texts: Sequence[str]
```

the output is broken 
![image](https://user-images.githubusercontent.com/36131443/135551060-83f8d0d2-3ef1-442f-8474-d3a96abe3e81.png)
 and pressing the submit button results in the following error 
`Whoops! There were some problems with your input: many_texts: field required`

**Problem and motivation:**

I have forms where some of the inputs are an arbitrary number of strings. Up until now I have solved this with a text_area widget, and prompt the user to separate their inputs with commas. Then with a custom validator the strings can be put back into a list. While this kinda works, it is a very hacky solution, it prevents me from using this package without breaking up my model

**Is this something you're interested in working on?**

Currently I don't have the capacity but it is something that am willing to look into in the near future (in a couple of months)

**Comment by LukasMasuch** [comment]
@papalotis Thanks for your feature suggestion. This is indeed broken when it is used with `pydantic_form` (instead of `pydantic_input`). The problem is that Streamlit currently does not provide any kind of input element that supports string lists. Streamlit supports list input only with the `multiselect` and the `file_uploader` widgets, but this does not help with string lists. Therefore, I had to combine multiple widget to support list inputs. However, this does not work within forms, since forms do not support interactive elements :(

One solution for that might be to use custom streamlit widgets (e.g. [streamlit-tags](https://github.com/gagan3012/streamlit-tags)), but I have to evaluate if that works with forms.

**Comment by LukasMasuch** [comment]
@disbr007 Thanks for your comment! There is no good workaround I know of at the moment since streamlit does not provide any widgets for multi-element inputs. But there might be a solution for this soon :)
